export const data = [
    {id: 1, age: 13, adress: 'Samarqand, Uzbekistan', name: 'Rahimjon', status: "Developer"},
    {id: 2, age: 13, adress: 'Samarqand, Uzbekistan', name: 'Kamron', status: "Engilish Teacher"},
    {id: 3, age: 13, adress: 'Samarqand, Uzbekistan', name: 'Asilbek', status: "Math Teacher"},
    {id: 4, age: 14, adress: 'Samarqand, Uzbekistan', name: 'Muhriddin', status: "Taxi"},
    {id: 5, age: 13, adress: 'Samarqand, Uzbekistan', name: 'Xumoyun', status: "Gorni"},
    {id: 6, age: 13, adress: 'Samarqand, Uzbekistan', name: 'Laziz', status: "Mebel"},
    {id: 6, age: 13, adress: 'Samarqand, Uzbekistan', name: 'Sardor', status: "Math Teacher"},
    {id: 7, age: 13, adress: 'Samarqand, Uzbekistan', name: 'Davlat', status: "car master"},
    {id: 8, age: 12, adress: 'Samarqand, Uzbekistan', name: 'Farruh', status: "biologiya uztoz"},
    {id: 9, age: 13, adress: 'Samarqand, Uzbekistan', name: 'Murod', status: "Hacker"},
    {id: 10, age: 14, adress: 'Samarqand, Uzbekistan', name: 'Begzod', status: "Beznesman"},
    {id: 11, age: 14, adress: 'Samarqand, Uzbekistan', name: 'Abduvahob', status: "Tadbirkor"},
    {id: 12, age: 14, adress: 'Samarqand, Uzbekistan', name: 'Javohir', status: "Math major"},
    {id: 13, age: 15, adress: 'Samarqand, Uzbekistan', name: 'Bexruz', status: "Engilish major"},
    {id: 7, age: 13, adress: 'Samarqand, Uzbekistan', name: 'Davlat', status: "car master"},
    {id: 8, age: 12, adress: 'Samarqand, Uzbekistan', name: 'Farruh', status: "biologiya uztoz"},
    {id: 9, age: 13, adress: 'Samarqand, Uzbekistan', name: 'Murod', status: "Hacker"},
    {id: 10, age: 14, adress: 'Samarqand, Uzbekistan', name: 'Begzod', status: "Beznesman"},
    {id: 11, age: 14, adress: 'Samarqand, Uzbekistan', name: 'Abduvahob', status: "Tadbirkor"},
    {id: 12, age: 14, adress: 'Samarqand, Uzbekistan', name: 'Javohir', status: "Math major"},
]